name: publish-npm-sdk-latest

on:
  push:
    tags:
      - 'web3mail-v*'

jobs:
  npm-publish:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      tag: 'latest'
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
